//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamExpeditors.PMD.ClientProxy
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "UserDetails", Namespace = "http://schemas.datacontract.org/2004/07/TeamExpeditors.PMD.DataContracts")]
    public partial class UserDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int CompanyIdField;

        private string CompanyNameField;

        private string EncryptedPasswordField;

        private string FirstNameField;

        private bool IsOwnerField;

        private string LastNameField;

        private Dashboard[] UserDashboardsField;

        private string UserEmailField;

        private int UserIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [DataMember()]
        public int CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }

        [DataMember()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }

        [DataMember()]
        public string EncryptedPassword
        {
            get
            {
                return this.EncryptedPasswordField;
            }
            set
            {
                this.EncryptedPasswordField = value;
            }
        }

        [DataMember()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }

        [DataMember()]
        public bool IsOwner
        {
            get
            {
                return this.IsOwnerField;
            }
            set
            {
                this.IsOwnerField = value;
            }
        }

        [DataMember()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }

        [DataMember()]
        public Dashboard[] UserDashboards
        {
            get
            {
                return this.UserDashboardsField;
            }
            set
            {
                this.UserDashboardsField = value;
            }
        }

        [DataMember()]
        public string UserEmail
        {
            get
            {
                return this.UserEmailField;
            }
            set
            {
                this.UserEmailField = value;
            }
        }

        [DataMember()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "Dashboard", Namespace = "http://schemas.datacontract.org/2004/07/TeamExpeditors.PMD.DataContracts")]
    public partial class Dashboard : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int DashboardIdField;

        private string DashboardNameField;

        private string DescriptionField;

        private int EndMonthField;

        private int EndYearField;

        private int StartMonthField;

        private int StartYearField;

        private AccessRight UserAccessRightField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [DataMember()]
        public int DashboardId
        {
            get
            {
                return this.DashboardIdField;
            }
            set
            {
                this.DashboardIdField = value;
            }
        }

        [DataMember()]
        public string DashboardName
        {
            get
            {
                return this.DashboardNameField;
            }
            set
            {
                this.DashboardNameField = value;
            }
        }

        [DataMember()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [DataMember()]
        public int EndMonth
        {
            get
            {
                return this.EndMonthField;
            }
            set
            {
                this.EndMonthField = value;
            }
        }

        [DataMember()]
        public int EndYear
        {
            get
            {
                return this.EndYearField;
            }
            set
            {
                this.EndYearField = value;
            }
        }

        [DataMember()]
        public int StartMonth
        {
            get
            {
                return this.StartMonthField;
            }
            set
            {
                this.StartMonthField = value;
            }
        }

        [DataMember()]
        public int StartYear
        {
            get
            {
                return this.StartYearField;
            }
            set
            {
                this.StartYearField = value;
            }
        }

        [DataMember()]
        public AccessRight UserAccessRight
        {
            get
            {
                return this.UserAccessRightField;
            }
            set
            {
                this.UserAccessRightField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "AccessRight", Namespace = "http://schemas.datacontract.org/2004/07/TeamExpeditors.PMD.DataContracts")]
    public partial class AccessRight : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AccessRightNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [DataMember()]
        public string AccessRightName
        {
            get
            {
                return this.AccessRightNameField;
            }
            set
            {
                this.AccessRightNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "Company", Namespace = "http://schemas.datacontract.org/2004/07/TeamExpeditors.PMD.DataContracts")]
    public partial class Company : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AccountField;

        private int CompanyIDField;

        private string NameField;

        private string UrlField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [DataMember()]
        public string Account
        {
            get
            {
                return this.AccountField;
            }
            set
            {
                this.AccountField = value;
            }
        }

        [DataMember()]
        public int CompanyID
        {
            get
            {
                return this.CompanyIDField;
            }
            set
            {
                this.CompanyIDField = value;
            }
        }

        [DataMember()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [DataMember()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "TeamExpeditors.PMD.ClientProxy.IUserLogin")]
    public interface IUserLogin
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserLogin/Authentication", ReplyAction = "http://tempuri.org/IUserLogin/AuthenticationResponse")]
        UserDetails Authentication(string userid, string pass);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserLogin/GetUserDashboards", ReplyAction = "http://tempuri.org/IUserLogin/GetUserDashboardsResponse")]
        Dashboard[] GetUserDashboards(int userID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserLogin/CreateNewDashboardByExistingDashboard", ReplyAction = "http://tempuri.org/IUserLogin/CreateNewDashboardByExistingDashboardResponse")]
        bool CreateNewDashboardByExistingDashboard(int dashboardID, int userID, string dashboardName, string description);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserLogin/ChangePassword", ReplyAction = "http://tempuri.org/IUserLogin/ChangePasswordResponse")]
        bool ChangePassword(int userid, string oldPassword, string newPassword);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserLoginChannel : IUserLogin, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserLoginClient : System.ServiceModel.ClientBase<IUserLogin>, IUserLogin
    {

        public UserLoginClient()
        {
        }

        public UserLoginClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public UserLoginClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public UserLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public UserLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public UserDetails Authentication(string userid, string pass)
        {
            return base.Channel.Authentication(userid, pass);
        }

        public Dashboard[] GetUserDashboards(int userID)
        {
            return base.Channel.GetUserDashboards(userID);
        }

        public bool CreateNewDashboardByExistingDashboard(int dashboardID, int userID, string dashboardName, string description)
        {
            return base.Channel.CreateNewDashboardByExistingDashboard(dashboardID, userID, dashboardName, description);
        }

        public bool ChangePassword(int userid, string oldPassword, string newPassword)
        {
            return base.Channel.ChangePassword(userid, oldPassword, newPassword);
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "TeamExpeditors.PMD.ClientProxy.IUserRegistration")]
    public interface IUserRegistration
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserRegistration/UserRegistration", ReplyAction = "http://tempuri.org/IUserRegistration/UserRegistrationResponse")]
        bool UserRegistration(UserDetails userDetails);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserRegistration/RetriveCompanyNames", ReplyAction = "http://tempuri.org/IUserRegistration/RetriveCompanyNamesResponse")]
        Company[] RetriveCompanyNames();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserRegistration/CompanyRegistration", ReplyAction = "http://tempuri.org/IUserRegistration/CompanyRegistrationResponse")]
        int CompanyRegistration(Company company);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserRegistrationChannel : IUserRegistration, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserRegistrationClient : System.ServiceModel.ClientBase<IUserRegistration>, IUserRegistration
    {

        public UserRegistrationClient()
        {
        }

        public UserRegistrationClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public UserRegistrationClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public UserRegistrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public UserRegistrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public bool UserRegistration(UserDetails userDetails)
        {
            return base.Channel.UserRegistration(userDetails);
        }

        public Company[] RetriveCompanyNames()
        {
            return base.Channel.RetriveCompanyNames();
        }

        public int CompanyRegistration(Company company)
        {
            return base.Channel.CompanyRegistration(company);
        }
    }
}
